# Generated by Django 2.2.7 on 2019-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocks',
            name='body_type',
            field=models.CharField(choices=[('text/html', 'html'), ('application/xml', 'xml'), ('application/json', 'json'), ('text/html', 'text'), ('image/jpeg', 'jpeg'), ('image/png', 'png'), ('other', 'other')], max_length=30, verbose_name='响应体类型'),
        ),
    ]
